name: audio_picker
description: A new Flutter project.
version: 0.0.1
author: chiragshenoy <chiragshenoy@gmail.com>
homepage: https://github.com/chiragshenoy/audio_picker

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.audio_picker.audio_picker
    pluginClass: AudioPickerPlugin
